const module = 'Favorite';

export const LOAD_ALL_FAVORITES_MOVIE_REQUEST = `${module}/LOAD_ALL_FAVORITES_MOVIE_REQUEST`;
export const LOAD_ALL_FAVORITES_MOVIE_SUCCESS = `${module}/LOAD_ALL_FAVORITES_MOVIE_SUCCESS`;
export const LOAD_ALL_FAVORITES_MOVIE_FAILURE = `${module}/LOAD_ALL_FAVORITES_MOVIE_FAILURE`;

export const LOAD_GENRES_REQUEST = `${module}/LOAD_GENRES_REQUEST`;
export const LOAD_GENRES_SUCCESS = `${module}/LOAD_GENRES_SUCCESS`;
export const LOAD_GENRES_FAILURE = `${module}/LOAD_GENRES_FAILURE`;

export const LOAD_MOVIE_REQUEST = `${module}/LOAD_MOVIE_REQUEST`;
export const LOAD_MOVIE_SUCCESS = `${module}/LOAD_MOVIE_SUCCESS`;
export const LOAD_MOVIE_FAILURE = `${module}/LOAD_MOVIE_FAILURE`;

export const DEL_FAVORITES_MOVIE_REQUEST = `${module}/DEL_FAVORITES_MOVIE_REQUEST`;
export const DEL_FAVORITES_MOVIE_SUCCESS = `${module}/DEL_FAVORITES_MOVIE_SUCCESS`;
export const DEL_FAVORITES_MOVIE_FAILURE = `${module}/DEL_FAVORITES_MOVIE_FAILURE`;

export default module;
