const module = 'Popular';

export const LOAD_NOW_PLAYING_MOVIE_REQUEST = `${module}/LOAD_NOW_PLAYING_MOVIE_REQUEST`;
export const LOAD_NOW_PLAYING_MOVIE_SUCCESS = `${module}/LOAD_NOW_PLAYING_MOVIE_SUCCESS`;
export const LOAD_NOW_PLAYING_MOVIE_FAILURE = `${module}/LOAD_NOW_PLAYING_MOVIE_FAILURE`;

export const LOAD_GENRES_REQUEST = `${module}/LOAD_GENRES_REQUEST`;
export const LOAD_GENRES_SUCCESS = `${module}/LOAD_GENRES_SUCCESS`;
export const LOAD_GENRES_FAILURE = `${module}/LOAD_GENRES_FAILURE`;

export const SEARCH_MOVIE_REQUEST = `${module}/SEARCH_MOVIE_REQUEST`;
export const SEARCH_MOVIE_SUCCESS = `${module}/SEARCH_MOVIE_SUCCESS`;
export const SEARCH_MOVIE_FAILURE = `${module}/SEARCH_MOVIE_FAILURE`;

export const ADD_TO_FAVORITES_REQUEST = `${module}/ADD_TO_FAVORITES_REQUEST`;
export const ADD_TO_FAVORITES_SUCCESS = `${module}/ADD_TO_FAVORITES_SUCCESS`;
export const ADD_TO_FAVORITES_FAILURE = `${module}/ADD_TO_FAVORITES_FAILURE`;

export const LOAD_ALL_FAVORITES_MOVIE_REQUEST = `${module}/LOAD_ALL_FAVORITES_MOVIE_REQUEST`;
export const LOAD_ALL_FAVORITES_MOVIE_SUCCESS = `${module}/LOAD_ALL_FAVORITES_MOVIE_SUCCESS`;
export const LOAD_ALL_FAVORITES_MOVIE_FAILURE = `${module}/LOAD_ALL_FAVORITES_MOVIE_FAILURE`;

export const DEL_FAVORITES_MOVIE_REQUEST = `${module}/DEL_FAVORITES_MOVIE_REQUEST`;
export const DEL_FAVORITES_MOVIE_SUCCESS = `${module}/DEL_FAVORITES_MOVIE_SUCCESS`;
export const DEL_FAVORITES_MOVIE_FAILURE = `${module}/DEL_FAVORITES_MOVIE_FAILURE`;

export const SET_FILTER = `${module}/SET_FILTER`;

export default module;
